config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  root to: 'about#index'
  resources :languages
  resources :traits
  resources :subraces
  resources :races
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trait.rb
class Trait < ApplicationRecord
  has_many :races
  validates :index, presence: true
  validates :url, presence: true
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
  before_action :set_trait, only: %i[ show edit update destroy ]

  # GET /traits or /traits.json
  def index
    @traits = Trait.all
  end

  # GET /traits/1 or /traits/1.json
  def show
  end

  # GET /traits/new
  def new
    @trait = Trait.new
  end

  # GET /traits/1/edit
  def edit
  end

  # POST /traits or /traits.json
  def create
    @trait = Trait.new(trait_params)

    respond_to do |format|
      if @trait.save
        format.html { redirect_to @trait, notice: "Trait was successfully created." }
        format.json { render :show, status: :created, location: @trait }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traits/1 or /traits/1.json
  def update
    respond_to do |format|
      if @trait.update(trait_params)
        format.html { redirect_to @trait, notice: "Trait was successfully updated." }
        format.json { render :show, status: :ok, location: @trait }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trait.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traits/1 or /traits/1.json
  def destroy
    @trait.destroy
    respond_to do |format|
      format.html { redirect_to traits_url, notice: "Trait was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trait
      @trait = Trait.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trait_params
      params.require(:trait).permit(:index, :races, :subraces, :name, :desc, :url)
    end
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/views/traits/_form.html.erb
<%= form_with(model: trait) do |form| %>
  <% if trait.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trait.errors.count, "error") %> prohibited this trait from being saved:</h2>

      <ul>
        <% trait.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/traits/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>Traits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traits.each do |trait| %>
      <tr>
        <td><%= trait.name %></td>
        <td><%= trait.desc %></td>
        <td><%= link_to 'Show', trait %></td>
        <td><%= link_to 'Destroy', trait, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trait', new_trait_path %>

app/views/traits/new.html.erb
<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>New Trait</h1>

<%= render 'form', trait: @trait %>

<%= link_to 'Back', traits_path %>

app/views/traits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<p>
  <strong>Name:</strong>
  <%= @trait.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @trait.desc %>
</p>

<%= link_to 'Back', traits_path %>