config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  root to: 'about#index'
  resources :languages
  resources :traits
  resources :subraces
  resources :races
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :subraces
  has_many :traits
  has_many :languages
  validates :index, presence: true
  validates :url, presence: true
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: %i[ show edit update destroy ]

  # GET /races or /races.json
  def index
    @races = Race.all
  end

  # GET /races/1 or /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races or /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: "Race was successfully created." }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1 or /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: "Race was successfully updated." }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1 or /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: "Race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def race_params
      params.require(:race).permit(:index, :name, :speed, :alignment, :age, :size, :size_desc, :languages, :language_desc, :traits, :subraces, :url)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_with(model: race) do |form| %>
  <% if race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
        <% race.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed %>
  </div>

  <div class="field">
    <%= form.label :alignment %>
    <%= form.text_field :alignment %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :size_desc %>
    <%= form.text_field :size_desc %>
  </div>

  <div class="field">
    <%= form.label :language_desc %>
    <%= form.text_field :language_desc %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>Races</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speed</th>
      <th>Age</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= race.speed %></td>
        <td><%= race.size %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>New Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @race.speed %>
</p>

<p>
  <strong>Alignment:</strong>
  <%= @race.alignment %>
</p>

<p>
  <strong>Age:</strong>
  <%= @race.age %>
</p>

<p>
  <strong>Size:</strong>
  <%= @race.size %>
</p>

<p>
  <strong>Size desc:</strong>
  <%= @race.size_desc %>
</p>

<p>
  <strong>Language desc:</strong>
  <%= @race.language_desc %>
</p>

<%= link_to 'Back', races_path %>