config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  root to: 'about#index'
  resources :languages
  resources :traits
  resources :subraces
  resources :races
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :race
  validates :index, presence: true
  validates :url, presence: true
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: %i[ show edit update destroy ]

  # GET /languages or /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1 or /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages or /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1 or /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1 or /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def language_params
      params.require(:language).permit(:index, :name, :type, :typical_speakers, :script, :url)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_with(model: language) do |form| %>
  <% if language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
        <% language.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lang_type %>
    <%= form.text_field :lang_type %>
  </div>

  <div class="field">
    <%= form.label :typical_speakers %>
    <%= form.text_field :typical_speakers %>
  </div>

  <div class="field">
    <%= form.label :script %>
    <%= form.text_field :script %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>Languages</h1>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Typical speakers</th>
      <th>Script</th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= language.lang_type %></td>
        <td><%= language.typical_speakers %></td>
        <td><%= language.script %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>New Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @language.lang_type %>
</p>

<p>
  <strong>Typical speakers:</strong>
  <%= @language.typical_speakers %>
</p>

<p>
  <strong>Script:</strong>
  <%= @language.script %>
</p>

<%= link_to 'Back', languages_path %>