config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  root to: 'about#index'
  resources :languages
  resources :traits
  resources :subraces
  resources :races
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subrace.rb
class Subrace < ApplicationRecord
  belongs_to :race
  validates :index, presence: true
  validates :url, presence: true
end

app/controllers/subraces_controller.rb
class SubracesController < ApplicationController
  before_action :set_subrace, only: %i[ show edit update destroy ]

  # GET /subraces or /subraces.json
  def index
    @subraces = Subrace.all
  end

  # GET /subraces/1 or /subraces/1.json
  def show
  end

  # GET /subraces/new
  def new
    @subrace = Subrace.new
  end

  # GET /subraces/1/edit
  def edit
  end

  # POST /subraces or /subraces.json
  def create
    @subrace = Subrace.new(subrace_params)

    respond_to do |format|
      if @subrace.save
        format.html { redirect_to @subrace, notice: "Subrace was successfully created." }
        format.json { render :show, status: :created, location: @subrace }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subrace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subraces/1 or /subraces/1.json
  def update
    respond_to do |format|
      if @subrace.update(subrace_params)
        format.html { redirect_to @subrace, notice: "Subrace was successfully updated." }
        format.json { render :show, status: :ok, location: @subrace }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subrace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subraces/1 or /subraces/1.json
  def destroy
    @subrace.destroy
    respond_to do |format|
      format.html { redirect_to subraces_url, notice: "Subrace was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subrace
      @subrace = Subrace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subrace_params
      params.require(:subrace).permit(:index, :name, :race, :desc, :ability_bonuses, :starting_proficiencies, :languages, :traits, :url)
    end
end

app/helpers/subraces_helper.rb
module SubracesHelper
end

app/views/subraces/_form.html.erb
<%= form_with(model: subrace) do |form| %>
  <% if subrace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subrace.errors.count, "error") %> prohibited this subrace from being saved:</h2>

      <ul>
        <% subrace.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subraces/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>Subraces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Race</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subraces.each do |subrace| %>
      <tr>
        <td><%= subrace.name %></td>
        <td><%= subrace.race %></td>
        <td><%= subrace.desc %></td>
        <td><%= link_to 'Show', subrace %></td>
        <td><%= link_to 'Destroy', subrace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subrace', new_subrace_path %>

app/views/subraces/new.html.erb
<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<h1>New Subrace</h1>

<%= render 'form', subrace: @subrace %>

<%= link_to 'Back', subraces_path %>

app/views/subraces/show.html.erb
<p><%= link_to 'Home', root_path %></p>

<%= link_to 'About', root_path %>
<%= link_to 'Races', races_url %>
<%= link_to 'Subraces', subraces_url %>
<%= link_to 'Traits', traits_url %>
<%= link_to 'Languages', languages_url %>

<p>
  <strong>Name:</strong>
  <%= @subrace.name %>
</p>

<p>
  <strong>Race:</strong>
  <%= @subrace.race %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @subrace.desc %>
</p>

<%= link_to 'Back', subraces_path %>